### ISSUE TITLE
[1.14.3] Can you add the mod name to the file?

### ISSUE THREAD

**Issue by kwpugh** [durability101/1.14.3#1]
Please add a mod name to your build script to include it in the jar file output so it can be readily identified in a modpack.

**Comment by ShayBox** [comment]
Next time I release an update I'll name the jars with the mod name.
The build process always outputs `output.jar`, so nothing is changed in code to fix that, I just rename them manually.
Modpacks also shouldn't be including coremods, but I suppose nothing is stopping them.
![image](https://user-images.githubusercontent.com/9505196/60308167-a306b700-9915-11e9-9b9d-980ef85a20d4.png)

**Comment by kwpugh** [comment]
Thanks.

You should be able to add the info in your build.gradle script, as the "archiveBaseName=" tag.


+++++++++++++++++++++++++

version = '2.1.27'
group = 'com.kwpugh.gobber2' // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = 'Gobber2-1.14.3'

++++++++++++++++++++++++++

results in Gobber2-1.14.3-2.1.27.jar at build
